= VPRO magnolia UI components
:toc:

image:https://github.com/vpro/magnolia-vpro-ui/workflows/build/badge.svg?[Build Status,link=https://github.com/vpro/magnolia-vpro-ui/actions?query=workflow%build]
image:https://img.shields.io/maven-central/v/nl.vpro/magnolia-vpro-ui.svg[MavenCentral,link=https://search.maven.org/search?q=g:%22nl.vpro%22]
// image:http://www.javadoc.io/badge/nl.vpro/magnolia-vpro-ui/.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro/magnolia-vpro-ui/]
// image:https://codecov.io/gh/vpro/magnolia-vpro-ui/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/vpro/magnolia-vpro-ui]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro/magnolia-vpro-ui.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/magnolia-vpro-ui/]

== Introduction

These are a few magnolia UI components which we developed mostly years ago. Recently we migrated to Magnolia 6 and its new framework, and we had
to migrate these components too. We took the occasion to isolate them to this github project. Hopefully it may benefit others, or otherwise it
may at least facilitate use showing our code.

Currently, there is no need yet to let this be an actual magnolia module.

SNAPSHOT's are present in sonatype.

.pom.xml dependency
[source,xml]
----
 <dependency>
  <groupId>nl.vpro</groupId>
  <artifactId>magnolia-vpro-ui</artifactId>
  <verrsion>1.0-SNAPSHOT</version>
 </dependency>
----
We'll make a release when we're ready, and the artifact will be available in maven central then.

Some components described below have extra dependencies, which will not come in automatically (they're optional), which is indicated in notes then.


== Fields
=== Color picker [[color_picker]]

Differences with: https://github.com/magnolia-community/color-picker-field

- stores as string, `String Color#getCSS`, rather than `int Color#getRGB`
- can show text field too (editable)
- more configurable
**  `text: <NOT|BEFORE|AFTER>`
**  `cssInPopup: <true: false>`
** `format: <HASH|RGB|RGBA>
** `pickerWidth: 100`
** `pickerHeight: 100`


.Example usage of color picker field in a form (described in yaml)
[source, yaml]
----
 color:
   $type: cssColorPickerField
   text: AFTER
   defaultValue: '#000'
   pickerWidth: 100
   pickerHeight: 100

----

=== EnumField [[enum_field]]

We provide a simpler version to use enums in a combobox.

.Example usage of enumField
[source, yaml]
----
 type:
    $type: enumField
    enum: nl.vpro.domain.koos.KoosTipType
----

Just specify as field $type `enumField`, and the name of the enum.

The enum is presented on default via its `toString` method, unless it implements `nl.vpro.i18n.Displayable`.



[NOTE]
====
Use following maven dependency if you want to use `Dispayable`

.vpro-i18n dependency
[source, xml]
----
<dependency>
  <groupId>nl.vpro.shared</groupId>
  <artifactId>vpro-shared-i18n</artifactId>
  <version>2.29.2</version>
</dependency>
----
====

If both of these are not desired (e.g. because you can't change the implementation of the enum), then you can set a `Converter` in the field definition or extend `nl.vpro.magnolia.ui.enumfield.EnumFieldDefinition` and overwrite `#convertToPresentation` (See e.g. the implementation of `$type: countryField` <<country_field>>)


===  Country field [[country_field]]

A drop down with countries of the world
[source, yaml]
----
 country:
   $type: countryField
----
Countries are displayed in current `Locale`, and stored as ISO 639 country code.

[NOTE]
====
For this to work you need

.nv-i18n dependency
[source, xml]
----
<dependency>
    <groupId>com.neovisionaries</groupId>
    <artifactId>nv-i18n</artifactId>
    <version>1.29</version>
</dependency>
----
====

=== IntegerRange [[integerrange_field]]

Just a drop down with integers

.Example of `integerRangeField`
[source, yaml]
----
fields:
  myinteger:
    $type: integerRangeField
    min: 3
    max: 11
----

=== Random UUID

Default readonly field containing a random UUID.

[source, yaml]
----
fields:
  uuid:
    $type: randomUUIDField
----

=== POMS media chooser

Shows a text field and a button. If you click on the button the POMS 'Media Selector' will be popped up, and you can select a media object. You'll need to log in poms

[source, yaml]
----
fields:
  media:
    $type: mediaChooserField
    mediaType:
      - BROADCAST
      - SERIES
----

[NOTE]
====
For this to work you need
[source, xml]
----
<dependency>
   <groupId>nl.vpro.media</groupId>
   <artifactId>media-domain</artifactId>
   <version>5.30.4</version>
</dependency>
----
and a property poms `poms.baseUrl=https://poms.omroep.nl/`
====


=== POMS types

A dropdown with types from POMS

[source, yaml]
----
fields:
  mediaType:
    $type: pomsTypesField
----

== Columns
=== ReferredColumn [[referred_column]]

Can be used as a column. Like so:

.Example of `referredColumn`
[source, yaml]
----
- name: author
  $type: referredColumn
  workspace: persons
  forType:
    - mgnl:vijverTip
  otherProperty: name
----

This can be used in workbench view to display a field in another nod. In this case a column `author` contains a reference to a node in the `persons` workspace, and rather then showing the `uuid` of the node, the `name` property of the referenced node is shown.


=== Unhtml column definition

[souce, yaml]
----
 description:
   $type: unhtmlColumn
----

[NOTE]
====
For this to work you need
[source, xml]
----
<dependency>
  <groupId>nl.vpro.shared</groupId>
  <artifactId>vpro-shared-util</artifactId>
  <version>2.29.2</version>
</dependency>
----
====

== Validators

=== Bean validation [[bean_validation]]

The idea is to use the link:https://beanvalidation.org/2.0/[`javax.validation`] framework

.Example usage of beanValidator validator.
[source, yaml]
----
validator:
   urlValidation:
      $type: beanValidator
      bean: nl.vpro.koos.KoosTip
      property: link
----

This way the validation of given bean property is 'borrowed', which is for example in this case exactly what we want, because the value will
end up there eventually.

[NOTE]
====
For this to work you need a validator implementation.

.Dependency on validator implementation
[source, xml]
----
<dependency>
  <groupId>org.hibernate.validator</groupId>
  <artifactId>hibernate-validator</artifactId>
  <version>6.2.1.Final</version>
</dependency>
----
====




