= VPRO magnolia UI components
:toc:

== Color picker

Differences with: https://github.com/magnolia-community/color-picker-field

- stores as string, `String Color#getCSS`, rather than `int Color#getRGB`
- can show text field too (editable)
- more configurable
**  `showText: <true|false>`
**  `pickerAfterText: <true|false>`
**  `cssInPopup: <true: false>`
** `pickerWidth: 100`
** `pickerHeight: 100`


=== Usage

[source, yaml]
----
 color:
   $type: cssColorPickerField
   showText: true
   pickerAfterText: true
   pickerWidth: 100
   pickerHeight: 100

----

== ReferredColumn

Can be used as a column. Like so:
[source, yaml]
----
- name: author
  $type: referredColumn
  workspace: persons
  forType:
    - mgnl:vijverTip
  otherProperty: name
----

This can be used in workbench view to display a field in another nod. In this case a column `author` contains a reference to a node in the `persons` workspace, and rather then showing the `uuid` of the node, the `name` property of the referenced node is shown.

== EnumField

We provide a simpler version to use enums in a combobox.

[source, yaml]
----
 type:
    $type: enumField
    enum: nl.vpro.domain.koos.KoosTipType
----

Just specify as field $type `enumField`, and the name of the enum.

The enum is presented on default via its `toString` method, unless it implements `nl.vpro.i18n.Displayable`.

If both of these are not desired (e.g. because you can't change the implementation of the enum), then you can set a `Converter` in the field definition or extend `nl.vpro.magnolia.ui.enumfield.EnumFieldDefinition` and overwrite `#convertToPresentation`

== bean validation

The idea is to use the `javax.validation` framework
[source, yaml]
----
validator:
   urlValidation:
      $type: beanValidator
      bean: nl.vpro.koos.KoosTip
      property: url
----
This is as yet untested

