= VPRO magnolia UI components
:toc:

image:https://github.com/vpro/magnolia-vpro-ui/workflows/build/badge.svg?[Build Status,link=https://github.com/vpro/magnolia-vpro-ui/actions?query=workflow%build]
image:https://img.shields.io/maven-central/v/nl.vpro/magnolia-vpro-ui.svg[MavenCentral,link=https://search.maven.org/search?q=g:%22nl.vpro%22]
// image:http://www.javadoc.io/badge/nl.vpro/magnolia-vpro-ui/.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro/magnolia-vpro-ui/]
// image:https://codecov.io/gh/vpro/magnolia-vpro-ui/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/vpro/magnolia-vpro-ui]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro/magnolia-vpro-ui.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/]

== Color picker

Differences with: https://github.com/magnolia-community/color-picker-field

- stores as string, `String Color#getCSS`, rather than `int Color#getRGB`
- can show text field too (editable)
- more configurable
**  `showText: <true|false>`
**  `pickerAfterText: <true|false>`
**  `cssInPopup: <true: false>`
** `pickerWidth: 100`
** `pickerHeight: 100`


=== Usage

[source, yaml]
----
 color:
   $type: cssColorPickerField
   showText: true
   pickerAfterText: true
   pickerWidth: 100
   pickerHeight: 100

----

== ReferredColumn

Can be used as a column. Like so:
[source, yaml]
----
- name: author
  $type: referredColumn
  workspace: persons
  forType:
    - mgnl:vijverTip
  otherProperty: name
----

This can be used in workbench view to display a field in another nod. In this case a column `author` contains a reference to a node in the `persons` workspace, and rather then showing the `uuid` of the node, the `name` property of the referenced node is shown.

== EnumField

We provide a simpler version to use enums in a combobox.

[source, yaml]
----
 type:
    $type: enumField
    enum: nl.vpro.domain.koos.KoosTipType
----

Just specify as field $type `enumField`, and the name of the enum.

The enum is presented on default via its `toString` method, unless it implements `nl.vpro.i18n.Displayable`.

If both of these are not desired (e.g. because you can't change the implementation of the enum), then you can set a `Converter` in the field definition or extend `nl.vpro.magnolia.ui.enumfield.EnumFieldDefinition` and overwrite `#convertToPresentation`

== bean validation

The idea is to use the `javax.validation` framework
[source, yaml]
----
validator:
   urlValidation:
      $type: beanValidator
      bean: nl.vpro.koos.KoosTip
      property: url
----
This is as yet untested

