= VPRO magnolia UI components
:toc:

image:https://github.com/vpro/magnolia-vpro-ui/workflows/build/badge.svg?[Build Status,link=https://github.com/vpro/magnolia-vpro-ui/actions?query=workflow%build]
image:https://img.shields.io/maven-central/v/nl.vpro/magnolia-vpro-ui.svg[MavenCentral,link=https://search.maven.org/search?q=g:%22nl.vpro%22]
// image:http://www.javadoc.io/badge/nl.vpro/magnolia-vpro-ui/.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro/magnolia-vpro-ui/]
// image:https://codecov.io/gh/vpro/magnolia-vpro-ui/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/vpro/magnolia-vpro-ui]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro/magnolia-vpro-ui.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/magnolia-vpro-ui/]

== Fields
=== Color picker [[color_picker]]

Differences with: https://github.com/magnolia-community/color-picker-field

- stores as string, `String Color#getCSS`, rather than `int Color#getRGB`
- can show text field too (editable)
- more configurable
**  `text: <NOT|BEFORE|AFTER>`
**  `cssInPopup: <true: false>`
** `format: <HASH|RGB|RGBA>
** `pickerWidth: 100`
** `pickerHeight: 100`


==== Usage

[source, yaml]
----
 color:
   $type: cssColorPickerField
   text: AFTER
   defaultValue: '#000'
   pickerWidth: 100
   pickerHeight: 100

----

=== EnumField [[enum_field]]

We provide a simpler version to use enums in a combobox.

[source, yaml]
----
 type:
    $type: enumField
    enum: nl.vpro.domain.koos.KoosTipType
----

Just specify as field $type `enumField`, and the name of the enum.

The enum is presented on default via its `toString` method, unless it implements `nl.vpro.i18n.Displayable`.



[NOTE]
====
Use following maven dependency if you want to use `Dispayable`
[source, xml]
----
<dependency>
  <groupId>nl.vpro.shared</groupId>
  <artifactId>vpro-shared-i18n</artifactId>
  <version>2.29.2</version>
</dependency>
----
====

If both of these are not desired (e.g. because you can't change the implementation of the enum), then you can set a `Converter` in the field definition or extend `nl.vpro.magnolia.ui.enumfield.EnumFieldDefinition` and overwrite `#convertToPresentation` (See e.g. the implementation of `$type: countryField` <<country_field>>)


===  Country field [[country_field]]

A drop down with countries of the world
[source, yaml]
----
 country:
   $type: countryField
----
Countries are displayed in current `Locale`, and stored as ISO 639 country code.

[NOTE]
====
For this to work you need
[source, xml]
----
<dependency>
    <groupId>com.neovisionaries</groupId>
    <artifactId>nv-i18n</artifactId>
    <version>1.29</version>
</dependency>
----
====

=== IntegerRange

Just a drop down with integers
[source, yaml]
----
 fields
  myinteger:
    $type: integerRangeField
    min: 3
    max: 11
----

== Columns
=== ReferredColumn [[referred_column]]

Can be used as a column. Like so:
[source, yaml]
----
- name: author
  $type: referredColumn
  workspace: persons
  forType:
    - mgnl:vijverTip
  otherProperty: name
----

This can be used in workbench view to display a field in another nod. In this case a column `author` contains a reference to a node in the `persons` workspace, and rather then showing the `uuid` of the node, the `name` property of the referenced node is shown.


=== Unhtml column definition

[souce, yaml]
----
 description:
   $type: unhtmlColumn
----

[NOTE]
====
For this to work you need
[source, xml]
----
<dependency>
  <groupId>nl.vpro.shared</groupId>
  <artifactId>vpro-shared-util</artifactId>
  <version>2.29.2</version>
</dependency>
----
====

== Validators

=== Bean validation [[bean_validation]]

The idea is to use the link:https://beanvalidation.org/2.0/[`javax.validation`] framework
[source, yaml]
----
validator:
   urlValidation:
      $type: beanValidator
      bean: nl.vpro.koos.KoosTip
      property: link
----

This way the validation of given bean property is 'borrowed', which is for example in this case exactly what we want, because the value will
end up there eventually.

[NOTE]
====
For this to work you need a validator implementation.
[source, xml]
----
<dependency>
  <groupId>org.hibernate.validator</groupId>
  <artifactId>hibernate-validator</artifactId>
  <version>6.2.1.Final</version>
</dependency>
----
====




