---
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        server-id: vpro-ossrh
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
        cache: maven
    - name: Build with Maven
      run: mvn -ntp -B -fn
      if: ${{ github.event_name == 'push' }}
    - name: Deploy with Maven
      run: mvn -ntp -B -Pdeploy  deploy -DskipTests=true
      if: ${{ github.event_name == 'push' }}
      env:
          SONATYPE_USERNAME: vpro
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

