---
name: release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: vpro-ossrh-release
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
          cache: maven
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          global: true
          name: 'github'
          email: 'digitaal-techniek@vpro.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: mvn -ntp -Pdeploy --batch-mode  -Darguments=-DskipTests  release:prepare release:perform
        env:
            SONATYPE_USERNAME: vpro
            SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
            GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

